name: QA Pipeline

on:
  #Ejecuta cuando subo cambios en la rama main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Prueba inicial
        run: echo "Mi primer workflow"

      - name: Ejecutando pruebas
        run: echo "Iniciando ejecucion"
